[package]
edition = "2021"
name    = "hodler-signal"
version = "0.1.0"


[workspace]
default-members = ["signal"]
members         = ["config", "exchange", "hodler", "signal"]


[[bin]]
name = "signal"
path = "src/main.rs"


[dependencies]
