[package]
edition = "2021"
name    = "server"
version = "0.1.0"


[dependencies]
axum   = { version = "0" }
config = { path = "../config" }
hodler = { path = "../hodler" }
serde  = { version = "1", features = ["derive"] }
